services:
  api_principal:
    build: .
    container_name: campus_seguro_principal
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    env_file:
      - .env

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    # O comando abaixo cria a ponte entre a internet e seu container
    command: tunnel --url http://campus_seguro_principal:8000